mindir_path: ./yolov8x_lite.mindir
port: /dev/ttyUSB0
baud: 115200
axis_drive_index: 0
axis_flywheel_index: 1
angle_kp: 350
angle_ki: 0.0
angle_kd: 0.7
angle_v_kp: 0.45
angle_v_ki: 0.0
angle_v_kd: 0.1
flywheel_speed_kp: 0.1
flywheel_speed_ki: 0.45
flywheel_speed_integral_limit:
- -400.0
- 400.0
socket_ip: 192.168.160.153
socket_ports: []
machine_middle_angle_init: -2.2
bike_turn_scale_deg: 0.057
bike_speed_scale_deg: 0.14
middle_angle_recitfy_limit_deg: 3.0
servo_center_deg: 8
servo_range_each_side_deg: 20
servo_speed_dps: 2
servo_step_time: 1000
flywheel_speed_limit: 25.0
flywheel_accel_limit: 15.0
roll_diff_limit: 0.1
march_velocity: 0.2
drive_accel: 0.1
person_safety_distance: 1.5
obstacle_safety_distance: 1
visualize: false
servo_middle_range: 2.0
servo_step_deg: 10
tacle_safety_distance: 1.0
